name: End-to-end tests
on:
  pull_request:
    branches:
      - '*'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Start server
        run: npm run preview &
        env:
          CI: true
      - name: Cypress run
        uses: cypress-io/github-action@v5